# Please DO NOT set the following properties `sonar.organization` and `sonar.projectKey` in this file. They must be stored as `SONAR_ORGANISATION_KEY` and `SONAR_PROJECT_KEY` GitHub secrets.

sonar.host.url=https://sonarcloud.io
sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8
sonar.sources=containers/backend/src,containers/frontend/src,lambdas/bedrock-prompt-messager/src
sonar.tests=containers/backend/src/__tests__,containers/frontend/src/__tests__,lambdas/bedrock-prompt-messager/src/__tests__,tests/playwright
sonar.exclusions=**/src/__tests__/**/*
sonar.terraform.provider.aws.version=5.54.1
sonar.cpd.exclusions=**/*.test.*,**/*.spec.*
sonar.coverage.exclusions=tests/**/*,**/*.dev.*,**/src/__tests__/**/*,containers/frontend/src/setupTests.js,containers/frontend/src/reportWebVitals.js,utils/utils/src/zod-validators.ts,**/jest.config.ts,scripts/**/*

#sonar.python.coverage.reportPaths=.coverage/coverage.xml
sonar.javascript.lcov.reportPaths=lcov.info
